name: Check Local Changes

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  check-local-changes:
    name: Check Local Changes
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      use-self-runner: false