name: Publish PR

on:
  workflow_run:
    workflows: [ 'Upload PR' ]
    types: [ completed ]
  issue_comment:
    types: [ edited ]
  pull_request_target:
    types: [ opened ]

permissions:
  packages: write
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish-pr:
    uses: ApexStudios-Dev/.github/.github/workflows/_publish-pr.yml@master
    secrets: inherit
    with:
      artifacts-base-path: apex-conventions/java/|apex-conventions/maven-publishing/|apex-conventions/neoforge-base/|apex-conventions/neoforge-legacy/|apex-conventions/neoforge/|apex-conventions/vanilla/|dev/apexstudios/ApexGradle/