name: Upload PR

on:
  pull_request_target:
    types:
      - synchronize
      - opened

jobs:
  upload-pr:
    name: Upload PR
    uses: ApexStudios-Dev/.github/.github/workflows/_upload-pr.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      use-self-runner: false